FROM alpine:edge

RUN apk update && \
    apk upgrade && \
    apk add --no-cache \
    openssl ca-certificates \
    zlib libxml2 glib gobject-introspection \
    libjpeg-turbo libexif lcms2 giflib libpng \
    libwebp orc tiff poppler-glib librsvg libgsf openexr && \
    rm -rf /var/cache/apk/*

COPY tmp/lib/ /usr/local/lib
COPY tmp/imaginary /usr/bin/imaginary

ENV PORT 9000
EXPOSE 9000

ENTRYPOINT ["/usr/bin/imaginary"]